apiVersion: v1
kind: Service
metadata:
  name: "hello-BUILD_NUMBER"
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-k8s
    version: "BUILD_NUMBER"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "hello-BUILD_NUMBER"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-k8s
        version: "BUILD_NUMBER"
    spec:
      containers:
        - name: hello-k8s
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

